name: Build & Deploy Hexo (befe -> main)

# 触发条件
on:
  push:
    branches:
      - befe          # 当你推送到 befe 分支时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 检出源代码（befe 分支）
      - name: Checkout source (befe)
        uses: actions/checkout@v4
        with:
          ref: befe

      # 2️⃣ 安装 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ 安装依赖（每次干净安装）
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Hexo 清理 & 生成网页
      - name: Clean & Generate
        run: |
          npx hexo clean
          npx hexo generate

      # 5️⃣ 部署到 main 分支（覆盖静态站点）
      - name: Deploy to main (Pages)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: main
          # 如果你绑定了域名
          cname: 
          # main 分支保留其他文件吗？false 表示覆盖
          keep_files: false
